services:
  postgres:
    image: timescale/timescaledb-ha:pg15-all
    shm_size: 512mb
    user: root
    ports:
      - 5435:5432
    environment:
      PGDATA: /var/lib/pg_data
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./output/.pg/data/pgdata:/var/lib/pg_data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

