name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_HOST_AUTH_METHOD: trust

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install psql
        run: |
          sudo apt-get update && sudo apt-get install -y lsb-release && sudo apt-get clean all;
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list';
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -;
          sudo apt-get update -y;
          sudo apt-get install -y postgresql-client libpq-dev;

      - name: Migration
        working-directory: ./services/migrations
        run: |
          echo '{ "type": "module" }' > 'package.json';
          npm install JAForbes/pgmg#e77436e6b93b39f0a4367db2352c29e3076c813d;
          npx pgmg postgres://postgres:password@localhost:5432/postgres migrations/*.js --prod;

      - name: Server Tests
        working-directory: ./services/server
        run: |
          npm install
          npm test
        env:
          TEST_DATABASE_URL: postgres://postgres:password@localhost:5432/postgres
          DATABASE_URL: postgres://zecret_api:password@localhost:5432/postgres
